### ISSUE TITLE
Gangnam Station Dataset Depthmap looks weird

### ISSUE THREAD

**Issue by bitterengsci** [naver/kapture#31]
Hi there,

I plot the depth map of Gangnam in color_jet using the following code, but the plot looks weird to me.

```
def plot_depth_heatmap(image, depth):   # heatmap RGB
    H, W = depth.shape
    if image.shape != depth.shape:
        image = cv2.resize(image, (W, H))

    heatmapimg = np.array(depth * 255, dtype = np.uint8)
    heatmapimg = cv2.applyColorMap(heatmapimg, cv2.COLORMAP_JET)

    heatmapimg[depth==0, :] = [0, 0, 0]

    img = np.concatenate((image, heatmapimg))

    return img


depth_r = np.fromfile(*.depth, dtype=np.float32).reshape(H, W)
returned_img = plot_depth_heatmap(RGBimg, depth_r)
```

I got figures like those, 

![Screenshot from 2021-09-09 19-25-19](https://user-images.githubusercontent.com/20001402/132677566-7b33e11a-b32a-4a86-8238-ad5939b4c534.png)
![Screenshot from 2021-09-09 19-25-29](https://user-images.githubusercontent.com/20001402/132677580-9ae4a52e-3a8e-4d34-81f7-fb95f7141dea.png)
![Screenshot from 2021-09-09 19-25-50](https://user-images.githubusercontent.com/20001402/132677587-ad7a2974-885a-4339-bc2f-105f772ddb97.png)

Please advice whether I did something incorrectly or this dataset itself contains depth info not good enough? Thanks in advance.

**Comment by humenbergerm** [comment]
Hi! The depth maps in this dataset are created by aggregating lidar scans. This results in sparse depth maps and some artefacts around moving objects. (Note that we will soon release a complete lidar scan per timestamp.)
However, that is not your problem, right? 
It seems like that the problem is here: heatmapimg = np.array(depth * 255, dtype = np.uint8)
The depth values are not between 0 and 1, but in absolute distances. So if you would like to have a depth map in the range of 0 and 255, you first have to normalize it between 0 and 1. 
Does this help or did I misunderstand something?

**Comment by bitterengsci** [comment]
> Hi! The depth maps in this dataset are created by aggregating lidar scans. This results in sparse depth maps and some artefacts around moving objects. (Note that we will soon release a complete lidar scan per timestamp.)
> However, that is not your problem, right?
> It seems like that the problem is here: heatmapimg = np.array(depth * 255, dtype = np.uint8)
> The depth values are not between 0 and 1, but in absolute distances. So if you would like to have a depth map in the range of 0 and 255, you first have to normalize it between 0 and 1.
> Does this help or did I misunderstand something?

Yep. Forgot to normalize, thanks... ^.^
