### ISSUE TITLE
format versioning

### ISSUE THREAD

**Issue by DoubleTwelve** [naver/kapture#41]
Hi, I've created a dataset as described in the documentation (using my own SW stack). I'd like to use kapture python toolbox for read operation on dataset, but I've found out that the toolbox expects additional information in the headers of csv files describing dataset format version. It is no brainer to add an extra line for me in my CSV generation code, but I think the documentation now it outdated and needs to be refreshed.

**Comment by yocabon** [comment]
Hi, thanks for the feedback.
Yes, since kapture 1.1 sensors.txt must start with # kapture format: 1.1
It's better to add it to all csv files.

Of note, for points3d.txt, there's a regression (we still have to decide how we'll fix that, fix the code or the spec); the short of it is that nowhere in the specification did we say that the second line # X, Y, Z or # X, Y, Z, R, G, B was mandatory but right now it creates issues when it's not here, like for https://github.com/naver/kapture/blob/main/samples/m1x/reconstruction/points3d.txt.
