### ISSUE TITLE
Conversion to colmap produces RADIAL

### ISSUE THREAD

**Issue by henrypearce4D** [naver/kapture#48]
I'm converting a bundler dataset with undistorted images to kapture, and then to colmap model files.

The resulting colmap model file cameras.txt uses the RADIAL camera model.

As the original dataset is an undistorted bundler, is there a way to define the resulting colmap files to be PINHOLE instead?

I tried converting the file in colmap using the "image_undistorter" command but this fails I presume because the RADIAL model has no values for lens distortion.

Any help would be much appreciated!

**Comment by jujumo** [comment]
Hi,

Thanks for sharing this issue.
I am not sure of what you intend to do, because I am not very familiar with bundler.
So, if  bundler cameras (images and intrinsics) are already undistorted, it should lead to null distortion coefficients.
But you are saying colmap fails to undistort images with null coefficient, right ?
AFAIK __colmap__ RADIAL model with null distortion coeff is equivalent to pinhole.
In that case, just replace `RADIAL w, h, f, cx, cy, k1, k2` with `PINHOLE w, h, fx, fy, cx, cy`, duplicating `f` to `fx` and `fy` and dropping ` k1`, `k2`  to , it should do the trick.

I hope it helps.
Let me know if I misunderstood the issue at hand.

**Comment by henrypearce4D** [comment]
Hi thankyou for this information I'll give that a go!
